# ***What is Numpy***




*   Numpy Stands for numerical python
*   Numpy is python library used for working in python array

*   It has funtions for working in domain linear algebra fourier transform, and matrices.

*  Numpy is created in 2005 by travis oliphant. it is open source so that any one can use it freely





**Why Numpy**

*   In python we have list instant of array that is very slow to process
*   Numpy is providing Array object that is 50X faster then ordinary list
*   array are frequntly used in data Science that why speed and resources are very important


Note== Numpay array is faster then list because numpy array are stored in continous place in memory unlike list

* Numpy is python library and its written partially in python but most of the part required fast  computation are written in C and C++





**Six Ways of Making Array**


1.   Array()

1.   linespace()

1.   longspace()
2.   arrange()

5.   zeros()

6.   ones()



***array()***

In [ ]:
from numpy import *
arr=array([1,2,3,4,7,3])
print(arr)

# if we convert one element of array of other type then all element will be converted to that type

arr1=array([1,2,3,2,4.1])
print(arr1)
print(arr1.dtype)

#another way of typecast to different datatype

arr2=array([6,8,3,4,6,9],float)
print(arr2)

[1 2 3 4 7 3]
[1.  2.  3.  2.  4.1]
float64
[6. 8. 3. 4. 6. 9.]


*Some operations in numpy array*

In [ ]:

arr=array([1,2,3,4,7])
arr=arr+5
print(arr)

[ 6  7  8  9 12]


In [ ]:
arrX=array([4,16,9,64])
arr2=array([17,7,11,13])
arr3=arrX+arr2
print(arr3)

[21 23 20 77]


In [ ]:
print(sqrt(arrX))
print(min(arrX))
print(max(arrX))
print(log(arrX))

[2. 4. 3. 8.]
4
64
[1.38629436 2.77258872 2.19722458 4.15888308]


concatenate two array

In [ ]:
ary1=array([1,3,5,6,11])
ary2=array([8,9,22,23,1])
print(concatenate([ary1,ary2]))

[ 1  3  5  6 11  8  9 22 23  1]


creating Two D array

In [ ]:
arrry=array([[1,2,3,4],[4,7,8,9]])
print(arrry)

[[1 2 3 4]
 [4 7 8 9]]


creating 3D array =You can create it with two 2D array

In [ ]:
arrry1=array([[[1,2,3],[4,5,0]],[[11,34,5],[12,34,67]]])
print(arrry1)

[[[ 1  2  3]
  [ 4  5  0]]

 [[11 34  5]
  [12 34 67]]]


Chaking Diamention of array

In [ ]:
a=array(11)
b=array([1,2,3,4])
c=array([[1,2,3],[6,7,8]])
d=array([[[1,2,2],[6,7,9]],[[1,1,0],[9,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Creating higher dimention array

In [ ]:
var1=array([1,3,5,6,7,8,3],ndmin=5)
print(var1.ndim)
print(var1)

5
[[[[[1 3 5 6 7 8 3]]]]]


In [ ]:
var2=array([[1,2,3],[6,7,9]],ndmin=5)
print(var2)

[[[[[1 2 3]
    [6 7 9]]]]]


Indexing in NumPy array

In [ ]:
num1=array([1,2,3,4,5,6])
num2=array([[1,2,3],[1,0,8]])
num3=array([[[1,7,0],[0,2,3]],[[1,9,7],[4,8,0]]])

print(num1[2])           #for one dimention array
print(num2[1,1])         #for two dimention array
print(num3[1,1,0])       #for three dimention array



print(num2[0][1])       # you can do slicing in this way


3
0
4
2


Negative indexing in Numpy array

In [ ]:
print(num1[-3])               #negative indexing in one dimention
print(num2[-1,-1])            #negative indexing in two dimention
print(num3[-1,-2,-1])         #negative indexing in three dimention

4
8
7


Slicing Numpay array

Slicing=[start:end]   note-end is excluded

slicing=[start:end:step]

1D array

In [ ]:
from IPython.core.application import ProfileDir
num3=array([1,2,4,5,6,8])
print("simple slicing")
print(num3[:4])
print(num3[1:])
print(num3[1:3])
print(num3[:])

#Negative Slicing
print("Slicing using negative index")
print(num3[:-3])
print(num3[-5:])
print(num3[-5:-2])


#including steps in slicing
print("slicing using step perameter")
print(num3[0:5:2])
print(num3[0:5:1])

#reversing a list using slicing
print("Inverse of list")
print(num3[::-1])

simple slicing
[1 2 4 5]
[2 4 5 6 8]
[2 4]
[1 2 4 5 6 8]
Slicing using negative index
[1 2 4]
[2 4 5 6 8]
[2 4 5]
slicing using step perameter
[1 4 6]
[1 2 4 5 6]
Inverse of list
[8 6 5 4 2 1]


Slicing in 2D array


                   0 1 2 3 4
              0  [[1,2,3,4,5]
              1   [5,8,9,0,10]
              2   [2,4,5,8,10]]             

In [ ]:
varr1=array([[1,3,5,8,9],[9,5,7,0,11],[0,7,8,5,7],[2,11,2,3,5]])
print(varr1)
print(varr1.ndim)
print("\n")
print(varr1[1:3])
print("\n")
print(varr1[2:3])
print("\n")
print(varr1[:3])


[[ 1  3  5  8  9]
 [ 9  5  7  0 11]
 [ 0  7  8  5  7]
 [ 2 11  2  3  5]]
2


[[ 9  5  7  0 11]
 [ 0  7  8  5  7]]


[[0 7 8 5 7]]


[[ 1  3  5  8  9]
 [ 9  5  7  0 11]
 [ 0  7  8  5  7]]


In [ ]:
# if we want first two column of 2D array
print(varr1[0:4,:2])



[[ 1  3]
 [ 9  5]
 [ 0  7]
 [ 2 11]]


In [ ]:
print(varr1)
# suppose we want part 5,7,3,5 out of 2D array
print(varr1[2:4,3:5])

[[ 1  3  5  8  9]
 [ 9  5  7  0 11]
 [ 0  7  8  5  7]
 [ 2 11  2  3  5]]
[[5 7]
 [3 5]]


`copying array`

*Aliasing* : If same memory block have more then one variable name is known as aliasing


In [ ]:
var12=array([1,3,4,5,8,9])
var13=var12
print(var13)
print(id(var12))
print(id(var13))

[1 3 4 5 8 9]
135863373352656
135863373352656


As you can see both array have same address therefore that means they are actually sharing same memory block this is known as Aliasing here we are not creating a shaperate array we are giving another name of same memory block

*`Shallow copy`* :-It means that it copy the element but still both copy will be dependent of each other

`note`:- for shallow copy in numpay array we use view() funtion

*Example*

In [ ]:
arr1=array([1,2,3,5,8,9])
arr2=arr1.view()
print(arr2)
arr2[2]=11
print(arr1)

[1 2 3 5 8 9]
[ 1  2 11  5  8  9]


In the above example you can see that on changing arr2 we find a change in arr1 automatically

Deep Copy: changes in one array will not effect the other array

*Example*

In [ ]:
arr1=[1,2,3,4,8]
arr2=arr1.copy()
arr2[0]=11
print(arr1)
print(arr2)

[1, 2, 3, 4, 8]
[11, 2, 3, 4, 8]


Here you can clearly see that change in copied array is not reflected in another array

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

`Numpy Array Shape`

*   The shape of an array is the number of elements in each dimension.
*   It simply return numbers of row and column inside a tuple



In [ ]:
var1=array([1,2,3,4])
var2=array([[1,3,5,6],[2,4,6,8]])
var3=array([[[1,7,8],[3,4,5]],[[2,4,5],[24,3,9]]])
print(var1.shape)
print(var2.shape)
print(var3.shape)

(4,)
(2, 4)
(2, 2, 3)


In the above example (2,4) tells that it is two dimention array and first dimention contain two element and second one consist four element.

In [ ]:
arr12=array([1,6,9,0,3,0,2],ndmin=5)
print(arr12.shape)

(1, 1, 1, 1, 7)


## `Reshaping Array`
1.   shape of array means number of element in each dimention
2.   Reshaping means changing the shape of array. by reshaping we can add or remove dimention or change number of element in each dimention



*coversion of 1D array to 2D array*

In [ ]:
arr1=array([1,5,7,8,9,4,3,3,4,0,4,2])
newarr=arr1.reshape(4,3)
print(newarr)

[[1 5 7]
 [8 9 4]
 [3 3 4]
 [0 4 2]]


*conversion of 1D array to 3D*

In [ ]:
arr24=array([1,3,4,5,6,4,3,2,1,0,33,11])
newarr12=arr24.reshape(2,3,2)
print(newarr12)

[[[ 1  3]
  [ 4  5]
  [ 6  4]]

 [[ 3  2]
  [ 1  0]
  [33 11]]]


*Rule for reshaping array*

you cannot reshape if the element required for reshaping is not sufficent suppose there is 8 element in array then you can create array of dimenetion (2,4) or (4,2) because 4*2 =8 that means elements are equal in both array

reshape give you view of array not copy of array

*`Unknown Dimension `*

You are allowed to have one unknown dimention that you are you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
xyz=array([1,9,0,22,11,2,3,4,6,7,2,1])
newarry=xyz.reshape(2,2,-1)
print(newarry)

[[[ 1  9  0]
  [22 11  2]]

 [[ 3  4  6]
  [ 7  2  1]]]


Flattening in array

Flattening array means converting multidimentional array in 1D

use reshape(-1) or flatten() funtion



In [ ]:
arr2D=array([[[1,2,4,5],[6,9,0,2],[1,0,8,4]],[[2,4,5,6],[1,9,0,4],[7,9,0,8]]])
print(arr2D.reshape(-1))
print(arr2D.flatten())

[1 2 4 5 6 9 0 2 1 0 8 4 2 4 5 6 1 9 0 4 7 9 0 8]
[1 2 4 5 6 9 0 2 1 0 8 4 2 4 5 6 1 9 0 4 7 9 0 8]
