## Iteration in Numpy

In [1]:
from numpy import *
arr1=array([1,9,0,8,7,4,5])
for i in arr1:
  print(i,end=" ")

1 9 0 8 7 4 5 

In [2]:
arr2=array([[1,2,3],[4,5,6],[0,9,1]])
for i in arr2:
  print(i)

[1 2 3]
[4 5 6]
[0 9 1]


In [3]:
arr3=array([[[1,2,3],[8,9,0],[0,8,2]],[[2,9,0],[2,0,3],[9,0,2]]])
print(arr3)
for i in arr3:
  print("It gives 2D array")
  print(i)


[[[1 2 3]
  [8 9 0]
  [0 8 2]]

 [[2 9 0]
  [2 0 3]
  [9 0 2]]]
It gives 2D array
[[1 2 3]
 [8 9 0]
 [0 8 2]]
It gives 2D array
[[2 9 0]
 [2 0 3]
 [9 0 2]]


## `Numpy Axis`       
                      --->
                      axix 1
                  [[1,2,3,0]
          axis 0   [2,0,3,4]
                   [1,1,0,0]]

In [4]:
arr23=array([[1,2,3],[4,5,7],[2,0,9]])
print(arr23)
print("sum of element of axis 0")
print(arr23.sum(axis=0))
print("sum of element of axis 1")
print(arr23.sum(axis=1))

[[1 2 3]
 [4 5 7]
 [2 0 9]]
sum of element of axis 0
[ 7  7 19]
sum of element of axis 1
[ 6 16 11]


for finding transpose of array

In [5]:
print(arr23.T)
print(arr23.nbytes)   #total bytes consumed

[[1 4 2]
 [2 5 0]
 [3 7 9]]
72


## Joining two arrays



In [6]:
arr8=array([1,23,11])
arr9=array([0,1,3])
print(concatenate((arr8,arr9)))

[ 1 23 11  0  1  3]


In [7]:
arr23=array([[1,2,3],[3,4,6]])
arr24=array([[7,8,9],[0,5,6]])
arr45=concatenate((arr23,arr24),axis=1)
print(arr45)

[[1 2 3 7 8 9]
 [3 4 6 0 5 6]]


In [8]:
arr46=concatenate((arr23,arr24),axis=0)
print(arr46)

[[1 2 3]
 [3 4 6]
 [7 8 9]
 [0 5 6]]


## Splitting Numpy arrays

In [9]:
arr11=array([1,5,7,9,8,0,2,4,2,2])
print(array_split(arr1,5))

[array([1, 9]), array([0, 8]), array([7]), array([4]), array([5])]


In [10]:
arr22=array([1,2,3,4,5,6])
list1=array_split(arr22,4)
print(list1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [11]:
print(list1[0])
print(list1[1])
print(list1[2])
print(list1[3])

[1 2]
[3 4]
[5]
[6]


In [12]:
arr33=array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
list2=array_split(arr33,3)
print(list2)
print(list2[0])
print(list2[1])
print(list2[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


## `Numpy Array Search`

where() it return list of index of element which satisfiy condition inside it

In [13]:
arr23=array([1,2,3,4,5,6,4,4])
x=where(arr23==4)
print(x)

(array([3, 6, 7]),)


In [14]:
# find index of even value
var1=array([1,2,3,4,5,6,7,8,9,10])
lst=where(var1%2==0)
print(lst)

#find index of odd value
lst1=where(var1%2!=0)
print(lst1)

(array([1, 3, 5, 7, 9]),)
(array([0, 2, 4, 6, 8]),)


## Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [15]:
from numpy import *
arr01=array([1,2,5,6])
x=searchsorted(arr01,5)
print(x)

2


if 5 will be in secand index then array will be as sorted as it was

`othercase`

Q)Find the indexes where the value 7 should be inserted, starting from the right:

In [16]:
arr02=array([6,7,8,9])
z=searchsorted(arr02,7,side="right")
print(z)

2


For multivalues

In [17]:
arr03=array([1,3,5,7])
y=searchsorted(arr03,[2,4,6])
print(y)

[1 2 3]


***`Sorting Numpy array`***

In [18]:
arr04=array([1,5,7,0,2])
print(sort(arr04))

[0 1 2 5 7]


This method return copy of array leaving the orignal array unchanged

In [19]:
arr05=array(["Apple","Riya","Nitya","Haldar"])
print(sort(arr05))

['Apple' 'Haldar' 'Nitya' 'Riya']


In [20]:
arr06=array([True,False,True])
print(sort(arr06))

[False  True  True]


In case of two D array each array is sorted individually

In [21]:
arr07=array([[1,2,0,3,2],[9,0,8,7,2]])
print(sort(arr07))

[[0 1 2 2 3]
 [0 2 7 8 9]]


# *`Filtering array`*

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

Notes:-A boolean index list is a list of booleans corresponding to indexes in the array.



In [24]:
arr09=array([41,44,99,0,4])
xyz=arr09[[True,False,True,True,False]]
print(xyz)

[41 99  0]


In [28]:
# if you want element from array which is less then 44

arr01=array([41,44,40,42,45])
xyz1=[]
for i in arr01:
  if i<44:
    xyz1.append(True)
  else:
    xyz1.append(False)

new=arr01[xyz1]
print(new)




[41 40 42]


In [29]:
#Q find even element from array
arr02=array([2,3,4,5,6,7,8])
xyz2=[]
for i in arr02:
  if i%2==0:
    xyz2.append(True)
  else:
    xyz2.append(False)
xyz=arr02[xyz2]
print(xyz)


[2 4 6 8]
